server:
  port: 8080

spring:
  application:
    name: moniotr-logstash
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/logstash
  level:
    root: info
