server:
  port: 9092

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.7.115:8848
        username: nacos
        password: nacos

logging:
  file:
    name: "logs/consumer.log"