server:
  port: 8080

spring:
  application:
    name: moniotr-actuator
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: info
