server:
  port: 9501

mybatis:
  type-aliases-package: org.noahsark.cache.model

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bell-lab?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.7.115
    port: 6379
