server:
  port: 8080
  servlet:
    context-path: /cas

spring:
  application:
    name: koala-cas-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.7.115:8848
        username: nacos
        password: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 120.79.235.83
    port: 6379
    # password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: debug